#include<stdio.h>
int main()
{
	int rdm;
	srand(time(0));
	rdm=rand()%100;
	//printf("%d",rdm);
	printf("				Guess The Number Game				\n");
	printf("\nFind the number from 1 to 100 that is generated by computer\n");
	printf("\nIf you guess the number u are winner otherwise u are looser\n");
	printf("\n\nPress any key to continue....\n\n");
	getch();
	system("cls");
	printf("				Guess The Number Game				\n");
	printf("\nChoose the difficulty level\n");
	printf("1. Easy\n");
	printf("2. Medium\n");
	printf("3. Difficult\n");
	printf("4. Exit");
	printf("\n\nU can choose from 1 to 4 \n\n");
	int ch,att,num;
	printf("Enter your choice: ");
	scanf("%d",&ch);
	switch(ch)
	{
		case 1:
		{
			for(att=10;att>=0;att--)
			{
				if(att==0)
				{
					printf("\nU loose the game!!\nBetter luck next time!!\n");
					break;
				}
				else
				{
					printf("\nU have %d attempts to guess the number\n",att);
					printf("Enter your number: ");
					scanf("%d",&num);
					if(num==rdm)
					{
						printf("\nU guessed the number!!\nU are winner!! congratulations!!\n");
						break;
					}
					else if(num>rdm)
						printf("\nMagic Number is smaller than %d\n",num);
					else if(num<rdm)
						printf("\nMagic Number is greater than %d\n",num);
				}
			}
			printf("%d is the number",rdm);
			break;
		}
		case 2:
		{
			for(att=7;att>=0;att--)
			{
				if(att==0)
				{
					printf("\nU loose the game!!\nBetter luck next time!!\n");
					break;
				}
				else
				{
					printf("\nU have %d attempts to guess the number\n",att);
					printf("Enter your number: ");
					scanf("%d",&num);
					if(num==rdm)
					{
						printf("\nU guessed the number!!\nU are winner!! congratulations!!\n");
						break;
					}
					else if(num>rdm)
						printf("\nMagic Number is smaller than %d\n",num);
					else if(num<rdm)
						printf("\nMagic Number is greater than %d\n",num);
				}
			}
			printf("%d is the number",rdm);
			break;
		}
		case 3:
		{
			for(att=5;att>=0;att--)
			{
				if(att==0)
				{
					printf("\nU loose the game!!\nBetter luck next time!!\n");
					break;
				}
				else
				{
					printf("\nU have %d attempts to guess the number\n",att);
					printf("Enter your number: ");
					scanf("%d",&num);
					if(num==rdm)
					{
						printf("\nU guessed the number!!\nU are winner!! congratulations!!\n");
						break;
					}
					else if(num>rdm)
						printf("\nMagic Number is smaller than %d\n",num);
					else if(num<rdm)
						printf("\nMagic Number is greater than %d\n",num);
				}
			}
			printf("%d is the number",rdm);
			break;
		}
		case 4:
			printf("\nExited from the game....\n");
			break;
		default:
			printf("Invalid Input\nChoose from 1 to 4");
	}
	return 0;
}
